# Generated by Django 5.2.11 on 2026-02-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_url', models.URLField(blank=True, max_length=500, null=True)),
                ('job_description', models.TextField()),
                ('match_score', models.IntegerField(blank=True, null=True)),
                ('tailored_resume', models.JSONField(blank=True, null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
