# Generated by Django 5.2.11 on 2026-05-24 07:31

from django.db import migrations, models


def backfill_application_status(apps, schema_editor):
    Application = apps.get_model("core", "Application")
    for application in Application.objects.all():
        if application.submitted:
            status = "submitted"
        elif application.tailored_resume or application.cover_letter:
            status = "kit_generated"
        elif application.match_score is not None:
            status = "matched"
        else:
            status = "draft"
        application.status = status
        application.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="ai_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="application",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="match_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="matching_skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="application",
            name="missing_skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="application",
            name="profile_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scraped", "Scraped"),
                    ("low_match", "Low Match"),
                    ("matched", "Matched"),
                    ("kit_generated", "Kit Generated"),
                    ("submitted", "Submitted"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="match_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_application_status, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["status", "-created_at"], name="core_applic_status_cd6f67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["submitted", "-created_at"],
                name="core_applic_submitt_f2efeb_idx",
            ),
        ),
    ]
