# Generated by Django 5.2.11 on 2026-05-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_public_agent_foundations"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review_required", "Review Required"),
                            ("ready", "Ready"),
                        ],
                        db_index=True,
                        default="review_required",
                        max_length=24,
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=240)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=80)),
                ("location", models.CharField(blank=True, max_length=240)),
                ("work_authorization", models.CharField(blank=True, max_length=240)),
                ("availability", models.CharField(blank=True, max_length=240)),
                ("linkedin_url", models.URLField(blank=True, max_length=500)),
                ("github_url", models.URLField(blank=True, max_length=500)),
                ("portfolio_url", models.URLField(blank=True, max_length=500)),
                ("extracted_profile", models.JSONField(blank=True, default=dict)),
                ("confirmed_profile", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_active", "-updated_at"],
                        name="core_candid_is_acti_bc8034_idx",
                    ),
                    models.Index(
                        fields=["status", "-updated_at"],
                        name="core_candid_status_c3c0a5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CandidatePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_roles", models.JSONField(blank=True, default=list)),
                ("target_locations", models.JSONField(blank=True, default=list)),
                ("remote_preferences", models.JSONField(blank=True, default=list)),
                ("salary_range", models.CharField(blank=True, max_length=160)),
                ("experience_level", models.CharField(blank=True, max_length=120)),
                ("work_authorization", models.CharField(blank=True, max_length=240)),
                ("availability", models.CharField(blank=True, max_length=160)),
                ("blocked_companies", models.JSONField(blank=True, default=list)),
                ("must_have_skills", models.JSONField(blank=True, default=list)),
                ("generated_queries", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="core.candidateprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("github", "GitHub"),
                            ("portfolio", "Portfolio"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("url", models.URLField(max_length=700)),
                ("label", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="core.candidateprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "link_type", "url")},
            },
        ),
        migrations.CreateModel(
            name="CandidateDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("resume", "Resume"),
                            ("cover_letter", "Cover Letter"),
                            ("certificate", "Certificate"),
                            ("project_summary", "Project Summary"),
                            ("publication", "Publication"),
                            ("transcript", "Transcript"),
                            ("other", "Other"),
                        ],
                        default="resume",
                        max_length=40,
                    ),
                ),
                ("original_filename", models.CharField(max_length=260)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("extracted", "Extracted"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("extracted_text_sample", models.TextField(blank=True)),
                ("extracted_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.candidateprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("resume_upload", "Resume Upload"),
                            ("document_upload", "Document Upload"),
                            ("link", "Link"),
                            ("local_folder", "Local Folder"),
                            ("manual", "Manual"),
                            ("ai_extraction", "AI Extraction"),
                        ],
                        max_length=40,
                    ),
                ),
                ("label", models.CharField(max_length=240)),
                ("uri", models.CharField(blank=True, max_length=700)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.candidatedocument",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.candidatelink",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_sources",
                        to="core.candidateprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("identity", "Identity"),
                            ("contact", "Contact"),
                            ("skill", "Skill"),
                            ("experience", "Experience"),
                            ("domain", "Domain"),
                            ("education", "Education"),
                            ("project", "Project"),
                            ("link", "Link"),
                            ("evidence_note", "Evidence Note"),
                        ],
                        max_length=40,
                    ),
                ),
                ("value", models.TextField()),
                ("normalized_value", models.CharField(db_index=True, max_length=260)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("evidence_text", models.TextField(blank=True)),
                ("confidence", models.PositiveSmallIntegerField(default=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("extracted", "Extracted"),
                            ("evidence_backed", "Evidence Backed"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="extracted",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="core.candidateprofile",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claims",
                        to="core.evidencesource",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["profile", "category", "status"],
                        name="core_profil_profile_22ce95_idx",
                    )
                ],
                "unique_together": {("profile", "category", "normalized_value")},
            },
        ),
    ]
