# Generated by Django 5.2.14 on 2026-05-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_candidateprofile_candidatepreference_candidatelink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="screenshot",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="tailored_resume_pdf",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="candidatepreference",
            name="auto_submit_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="candidatepreference",
            name="resume_source",
            field=models.CharField(default="claims", max_length=40),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scraped", "Scraped"),
                    ("low_match", "Low Match"),
                    ("matched", "Matched"),
                    ("kit_generated", "Kit Generated"),
                    ("submitted", "Submitted"),
                    ("failed", "Failed"),
                    ("auto_applied", "Auto Applied"),
                    ("manual_required", "Manual Required"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
