# Generated by Django 5.2.14 on 2026-06-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_pipeline_and_llm_usage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecureCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=120, unique=True)),
                ("encrypted_value", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name="llmusageevent",
            new_name="core_llmusa_created_b46d53_idx",
            old_name="core_llmusa_created_6e0f0d_idx",
        ),
        migrations.RenameIndex(
            model_name="llmusageevent",
            new_name="core_llmusa_task_ty_5c3f34_idx",
            old_name="core_llmusa_task_ty_8c8f1a_idx",
        ),
        migrations.RenameIndex(
            model_name="pipelinejob",
            new_name="core_pipeli_kind_2fbc6e_idx",
            old_name="core_pipeli_kind_4a8b2c_idx",
        ),
    ]
