# Generated by Django 5.2.14 on 2026-06-03 16:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_securecredential_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRunLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_name", models.CharField(db_index=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("detail_data", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_logs",
                        to="core.application",
                    ),
                ),
                (
                    "job_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_logs",
                        to="core.joblead",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["agent_name", "-created_at"],
                        name="core_agentr_agent_n_2c9eb4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CandidateQuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "normalized_question",
                    models.CharField(db_index=True, max_length=260),
                ),
                ("answer_text", models.TextField()),
                (
                    "category",
                    models.CharField(db_index=True, default="general", max_length=80),
                ),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_items",
                        to="core.candidateprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "normalized_question")},
            },
        ),
    ]
