# Generated by Django 5.2.14 on 2026-06-05 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_agentrunlog_candidatequestionanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="core.candidateprofile",
            ),
        ),
        migrations.AddField(
            model_name="candidatepreference",
            name="resume_font_size",
            field=models.FloatField(default=10.5),
        ),
        migrations.AddField(
            model_name="candidatepreference",
            name="resume_line_height",
            field=models.FloatField(default=1.35),
        ),
        migrations.AddField(
            model_name="candidatepreference",
            name="resume_margin_bottom",
            field=models.FloatField(default=0.75),
        ),
        migrations.AddField(
            model_name="candidatepreference",
            name="resume_margin_left",
            field=models.FloatField(default=0.75),
        ),
        migrations.AddField(
            model_name="candidatepreference",
            name="resume_margin_right",
            field=models.FloatField(default=0.75),
        ),
        migrations.AddField(
            model_name="candidatepreference",
            name="resume_margin_top",
            field=models.FloatField(default=0.75),
        ),
        migrations.AddField(
            model_name="candidatepreference",
            name="resume_theme",
            field=models.CharField(default="modern_sans", max_length=40),
        ),
        migrations.AddField(
            model_name="joblead",
            name="matched_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_leads",
                to="core.candidateprofile",
            ),
        ),
    ]
