# Generated by Django 5.2.14 on 2026-06-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_application_profile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                ("display_name", models.CharField(max_length=120)),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                ("api_key_name", models.CharField(max_length=80)),
                ("base_url", models.URLField(blank=True, max_length=500)),
                (
                    "adapter_type",
                    models.CharField(default="openai_compatible", max_length=80),
                ),
                (
                    "credit_status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("low", "Low"),
                            ("exhausted", "Exhausted"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=24,
                    ),
                ),
                ("estimated_balance_usd", models.FloatField(blank=True, null=True)),
                ("last_balance_check", models.DateTimeField(blank=True, null=True)),
                ("credit_exhausted_at", models.DateTimeField(blank=True, null=True)),
                ("extra_headers", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("models", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["priority", "provider_name"],
            },
        ),
    ]
