from django.urls import path
from . import views

urlpatterns = [
    path('', views.profile_setup, name='profile_setup'),
    path('onboarding/documents/', views.onboarding_documents, name='onboarding_documents'),
    path('onboarding/links/', views.onboarding_links, name='onboarding_links'),
    path('onboarding/preferences/', views.onboarding_preferences, name='onboarding_preferences'),
    path('profile/evidence/', views.profile_evidence, name='profile_evidence'),
    path('profile/review/', views.profile_review, name='profile_review'),
    path('jobs/', views.job_discovery, name='job_discovery'),
    path('jobs/queue/', views.job_queue, name='job_queue'),
    path('jobs/discover/', views.run_discovery, name='run_discovery'),
    path('jobs/bulk-score/', views.bulk_score_leads, name='bulk_score_leads'),
    path('jobs/bulk-generate/', views.bulk_generate_kits_view, name='bulk_generate_kits'),
    path('jobs/discovery-status/', views.discovery_status, name='discovery_status'),
    path('jobs/import/', views.import_job, name='import_job'),
    path('jobs/dismiss/', views.dismiss_lead, name='dismiss_lead'),
    path('jobs/generate/', views.generate_kit, name='generate_kit'),
    path('jobs/submit/', views.mark_submitted, name='mark_submitted'),
    path('applications/', views.applications_dashboard, name='applications_dashboard'),
    path('metrics/', views.metrics_dashboard, name='metrics_dashboard'),
    path('pipeline/<int:job_id>/cancel/', views.cancel_pipeline_job, name='cancel_pipeline_job'),
    path('settings/providers/', views.provider_settings, name='provider_settings'),
    path('settings/channels/', views.channel_settings, name='channel_settings'),
    path('integrations/telegram/webhook/', views.telegram_webhook, name='telegram_webhook'),
    path('integrations/discord/interactions/', views.discord_interactions, name='discord_interactions'),
    path('jobs/agent-logs/<str:obj_type>/<int:obj_id>/', views.agent_logs, name='agent_logs'),
    path('profile/qa/', views.qa_dashboard, name='qa_dashboard'),
    path('profile/qa/verify/', views.verify_qa_item, name='verify_qa_item'),
]
